/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoBlock: typeof import('./src/components/DemoBlock.vue')['default']
    DocFooterNav: typeof import('./src/components/DocFooterNav.vue')['default']
    DocsContent: typeof import('./src/components/layout/DocsContent.vue')['default']
    DocsHeader: typeof import('./src/components/layout/DocsHeader.vue')['default']
    DocsLayout: typeof import('./src/components/layout/DocsLayout.vue')['default']
    DocsOutline: typeof import('./src/components/DocsOutline.vue')['default']
    DocsSearch: typeof import('./src/components/DocsSearch.vue')['default']
    DocsSider: typeof import('./src/components/layout/DocsSider.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LuluButton: typeof import('@lulu/vue/button')['default']
    PlaceholderPage: typeof import('./src/components/PlaceholderPage.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    SiteSidebar: typeof import('./src/components/SiteSidebar.vue')['default']
    ThemePlayground: typeof import('./src/components/ThemePlayground.vue')['default']
  }
}
